config/routes.rb
Rails.application.routes.draw do



  resources :contact_forms
  get "pricing/" => "subscription_packs#pricing", as: :pricing
  get "portfolio/cards/:portfolio_id" => "cards#index", as: :portfolio_cards
  resources :cards do    
    get "delete"
  end

  get "invitations/search-users" => "invitations#search_users", as: :search_users

  get "members/organization/:organization_id" => "members#index", as: :organization_members

  resources :members do    
    get "delete"
  end
  resources :invitations do    
    get "delete"

    collection do    
      get "get_services" => "invitations#get_services"
    end
  end
  resources :pages do    
    get "delete"
  end
  
  resources :portfolios do    
    get "delete"
  end

  get "services/organization/:organization_id" => "services#index", as: :organization_services
  post "subscriptions/new" => "subscriptions#new_guest_subscription"
  get "subscriptions/new" => "subscriptions#new_guest_subscription", as: :new_guest_subscription


  #post "subscriptions/new"

  resources :services do    
    get "delete"
  end

  resources :organizations  do    
    get "delete"
  end
  resources :smtp_configs
  resources :organization_types  do    
    get "delete"
  end
  resources :subscriptions  do    
    get "delete"
  end
  resources :subscription_types do    
    get "delete"
  end
  resources :subscription_pack_items do    
    get "delete"
  end
  resources :subscription_packs do    
    get "delete"
  end
  
  resources :subscription_pack_features do    
    get "delete"
  end
  
  resources :activity_fields do    
    get "delete"
  end
  
  resources :permission_items do    
    get "delete"
  end
  resources :features do    
    get "delete"
  end
  

  
  
 
  
  resources :addresses do    
    get "delete"
  end
  
  # Home route.
  root to: "front#home"

  
  get '/robots.:format' => 'pages#robots'
  get '/ads.:format' => 'pages#ads'


  # Named routes.
  get "/home" => "front#home"
  get "/dashboard" => "dashboard#index", as: :dashboard
  get "/landing" => "pages#landing_page", as: :landing_page
  get "/inquiry-success" => "inquiry_forms#success", as: :inquiry_success
  get "/contact-success" => "contact_forms#success", as: :contact_success
  get "ad/success" => "ads#success", as: :ad_success
  get "/subscription-success" => "subscriptions#success", as: :subscription_success

  get "/suscribe" => "pages#newsletter_suscribe", as: :suscribe
  get "/post/:slug" => "blog#show", as: :post_show
  
  get "/search" => "searches#search_properties", as: :search_properties
  
  get "/about-us" => "pages#about_us", as: :about_us
  get "/how-it-work" => "pages#how_it_work", as: :how_it_work
  get "/cgu" => "pages#cgu", as: :cgu
  get "/join-us" => "pages#join_us", as: :join_us
  get "/contact" => "pages#contact", as: :contact
  get "/advertise" => "pages#advertise", as: :advertise
  get "/blog"  => "blog#index", as: :blog
  get "/faq" => "pages#faq", as: :faq
  get "/privacy-policy" => "pages#privacy_policy", as: :privacy_policy
  get "/partenaires" => "pages#partenaires", as: :partnaires
  
  #get '/inquiry_form' => 'contact_email#inquiry', as: :inquiry_email
  #get "/properties/all" => "front#properties", as: :load_all_properties
  get "/profile/:login/edit" => "profile#edit", as: :user_profile
  get 'users/edit' => 'users/registrations#edit', as:  :edit_user_registration
  #get "search" => "properties#search", as: :search_properties
  get "/user/enable/:id" => "custom_users#get_enable", as: :get_enable_user_account
	post "/user/enable/:id" => "custom_users#post_enable", as: :post_enable_user_account
	get "/user/disable/:id" => "custom_users#get_disable", as: :get_disable_user_account
  post "/user/disable/:id" => "custom_users#post_disable", as: :post_disable_user_account
  

  get "/users"     => "custom_users#index", as: :all_users 
  get "/users/unregistered"     => "custom_users#unregistered", as: :unregistered_commission_percentage 
  post "/users/new"     => "custom_users#create", as: :create_user
  get "/users/new"     => "custom_users#new", as: :new_user
  get "/user/edit/:id" => "custom_users#edit", as: :edit_user
  patch "/user/update/:id" => "custom_users#update", as: :udapte_user
  delete "/user/destroy/:id" => "custom_users#destroy", as: :destroy_user
  get "/user/delete/:id" => "custom_users#delete", as: :delete_user

 
  
  scope "account" do 
    resources :profiles 
    get "profile/:uid" => "profiles#edit", as: :edit_account
  end
  #devise_for :users
  resources :permission_roles do 
    get "delete"
  end
  resources :permissions do 
    get "delete"
  end
  resources :roles do 
    get "delete"
  end

  devise_for :users, path: '', controllers: { 
    registrations: "users/registrations",
    confirmations: 'users/confirmations',
    passwords: "users/passwords",
    sessions: "users/sessions"
        
    }, 
    path_names: {
        sign_in: 'login', 
        sign_out: 'logout', 
        password: 'secret', 
        confirmation: 'verification', 
        unlock: 'unblock', 
        registration: 'signup', 
        sign_up: '' 
  }

  devise_scope :user do
    #root to: "users/sessions#new"
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end
 
  # Dynamic error pages
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"
  mount Ckeditor::Engine => '/ckeditor'


  # For mobile API Endpoint
  mount API::Base, at: "/"

end

app/models/subscription.rb
# == Schema Information
#
# Table name: subscriptions
#
#  id                   :bigint           not null, primary key
#  uid                  :string
#  user_id              :bigint
#  subscription_pack_id :bigint
#  subscription_type_id :bigint
#  start_date           :datetime
#  end_date             :datetime
#  quantity             :integer
#  status               :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#

class Subscription < ApplicationRecord
	# Include shared utils.
  include SharedUtils::Generate

  before_save :generate_random_number_uid
  
  belongs_to :user
  belongs_to :subscription_pack
  belongs_to :subscription_type
end

app/models/subscription_type.rb
# == Schema Information
#
# Table name: subscription_types
#
#  id          :bigint           not null, primary key
#  uid         :string
#  name        :string
#  description :text
#  status      :string
#  user_id     :bigint
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class SubscriptionType < ApplicationRecord
	# Include shared utils.
  include SharedUtils::Generate

  before_save :generate_random_number_uid
  
  belongs_to :user
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  layout "front"
  before_action :set_subscription, only: %i[ show edit update destroy ]

  before_action :set_subscription_pack, only: %i[new_guest_subscription]

  # GET /subscriptions or /subscriptions.json
  def index
    @subscriptions = current_user.subscriptions
    render layout: "dashboard"
  end

  # GET /subscriptions/1 or /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription_packs = SubscriptionPack.all
    @subscription_types = SubscriptionType.all
    @subscription = Subscription.new
    #render layout: "front"
  end

  def new_guest_subscription
    puts "SUBSCRPTION PLAN: #{@subscription_pack}"
    @subscription_packs = SubscriptionPack.all
    @selected_pack = SubscriptionPack.find_by(uid: @subscription_pack.uid)
    @subscription_types = SubscriptionType.all

    if subscription_params
      create 
      return
    end

    @subscription = Subscription.new
    #render :new_guest_subscription

    #render layout: "front"
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions or /subscriptions.json
  def create
    puts "PARAMS: #{params[:action]}"
    @subscription = current_user.subscriptions.build(subscription_params)

    if params[:pack]
      @subscription.subscription_pack_id = SubscriptionPack.find_by(uid: params[:pack]).id
      
    end

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to subscription_success_path, notice: "Subscription was successfully created." }
        format.json { render :show, status: :created, location: @subscription }
        format.js
      else

          @subscription_packs = SubscriptionPack.all
          @selected_pack = SubscriptionPack.find_by(uid: @subscription_pack.uid)
          @subscription_types = SubscriptionType.all

          if params[:action] == "new_guest_subscription"
            format.html { render :new_guest_subscription, status: :unprocessable_entity }

          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @subscription.errors, status: :unprocessable_entity }
            format.js
          end
      end
    end
  end

  def success
  end

  # PATCH/PUT /subscriptions/1 or /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: "Subscription was successfully updated." }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1 or /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: "Subscription was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    def set_subscription_pack
      @subscription_pack = SubscriptionPack.find_by(uid: params[:pack])
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      if params[:subscription].nil? || params[:subscription].empty?
       false
      else
        params.require(:subscription).permit(:subscription_pack_id, :subscription_type_id, :quantity, :status)
      end
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_create.js.erb
$("ul.errors").html("");
<% if @subscription.errors.any? %>
  <% @subscription.errors.full_messages.each do |message| %>
 
    $("ul.errors").append($('<div class="c-alert c-alert--danger" > ').html("<%= message.html_safe %> "));
  <% end %>
<% else %>
  $(".subscriptions").html("<%= escape_javascript(render 'index') %>");
  $("#subscription-modal").modal("hide");
 
<% end %>

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription, local: false) do |form| %>
 <div class="modal-body">
    <ul class="errors">
    </ul>

  <div class="form-group">
    <%= form.label :subscription_pack_id, "Plan d'abonnement" %>
    <%= form.collection_select(:subscription_pack_id, @subscription_packs, :id, :name, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%") %> 

  </div>

  <div class="form-group">
    <%= form.label :subscription_type_id, "Type d'abonnement" %>
    <%= form.collection_select(:subscription_type_id, @subscription_types, :id, :name, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%") %> 

  </div>

  

  </div><!-- modal body -->
  <div class="modal-footer">
    <%= link_to "Annuler", "#", class: "btn btn-secondary tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1", data: {dismiss: "modal"} %>
    <%= form.submit  class: "btn btn-primary tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1",  "data-loading-text"=>"Loading...", autocomplete: "off" %>
  </div>
<% end %>

app/views/subscriptions/_guest_subscription_form.html.erb
<%= form_with(model: subscription, local: true, url: new_guest_subscription_path(pack: @subscription_pack.uid)) do |form| %>
<% if subscription.errors.any? %>
    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>

      <ul>
      <% subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="form-group">
    <%= form.label :subscription_pack_id, "Plan d'abonnement", class: "required" %>
    <%= form.collection_select(:subscription_pack_id, @subscription_packs, :id, :name, {prompt: "Sélectionner", :selected => @selected_pack.name}, class: "form-control", style: "width: 100%", disabled: true) %> 

  </div>

  <div class="form-group">
    <%= form.label :price, "Prix (F CFA)", class: "required" %>
    <%= form.number_field :price, value: @selected_pack.price, class: "form-control",  disabled: true %> 

  </div>

  <div class="form-group">
    <%= form.label :subscription_type_id, "Type d'abonnement", class: "required" %>
    <%= form.collection_select(:subscription_type_id, @subscription_types, :id, :name, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%", required: true) %> 

  </div>

  <div class="form-group">
    <%= form.label :quantity, "Quantité", class: "required" %>
    <%= form.number_field :quantity, class: "form-control", min: 1, step: :any, required: true %> 

  </div>

  

 
  <div class="form-group pull-right">
   
    <%= form.submit "Valider", class: "btn btn-primary tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1",  "data-loading-text"=>"Loading...", autocomplete: "off" %>
  </div>
<% end %>

app/views/subscriptions/_index.html.erb
<% @subscriptions.each do |subscription| %>
  <tr>
   
    <td><%= subscription.subscription_pack.name %></td>
    <td><%= subscription.subscription_type.name if subscription.subscription_type %></td>
   
    <td>
        <div class="action-buttons">
            <%= link_to raw('<i class="fa fa-pencil" aria-hidden="true"></i>
'),  edit_subscription_path(subscription), title: "Modifier", remote: true %>




<%= link_to raw('<i class="fa fa-trash-o" aria-hidden="true"></i>
'), subscription_delete_path(subscription), remote: true, title: "Supprimer", class: "delete" %>
</div>
</td>
  </tr>
<% end %>

app/views/subscriptions/_new.html.erb
<!-- Modal -->

  <div class="modal-dialog modal-lg">
    <div class="modal-content ">
      <div class="modal-header pd-y-20 pd-x-25">
            <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Nouveau - Abonnement</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

            <%= render 'form', subscription: @subscription %>
</div>
  </div>

app/views/subscriptions/create.js.erb
<%= render "create" %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<div class="br-pageheader mg-30">
      <nav class="breadcrumb pd-0 mg-0 tx-12">
        
        <span class="breadcrumb-item active"><h5>Abonnements</h5></span>
      </nav>
</div><!-- br-pageheader -->
<div class="br-pagebody">
  <div class="br-section-wrapper">
    <div class="headers mg-b-20">
        <div class="left-content">
        </div>

        <div class="text-right">
            <%= link_to raw('<i class="fa fa-plus" aria-hidden="true"></i> Ajouter'), new_subscription_path, class: "btn btn-primary tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1", remote: true %>

        </div>

    </div>


<table id="datatable1" class="table display responsive nowrap">


  <thead>
    <tr>
      
      <th>Plan d'abonnement</th>
      <th>Type d'abonnement</th>
      
      <th>Actions</th>
    </tr>
  </thead>

  <tbody class="subscriptions">
    <%= render "index" %>
  </tbody>
</table>

</div>
</div>
<div id="subscription-modal" class="c-modal modal fade" data-backdrop="static"></div>

app/views/subscriptions/new.js.erb
$("#subscription-modal").html("<%= escape_javascript(render 'new') %>");
$("#subscription-modal").modal("show");

app/views/subscriptions/new_guest_subscription.html.erb
<div id="new-guest-subscription">
    <div class="container ">
       
        <div class="br-pagebody mg-30">
            <div class="br-section-wrapper">
                <div class="headers mg-b-10">
                    <h2>Abonnement</h2>
                    <h6>Veuillez renseigner le formulaire ci-dessous!</h6>
                    <hr />
                </div>
                <%= render 'guest_subscription_form', subscription: @subscription %>
            </div>
        </div>  
    </div>
</div>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @subscription.user %>
</p>

<p>
  <strong>Subscription pack:</strong>
  <%= @subscription.subscription_pack %>
</p>

<p>
  <strong>Status:</strong>
  <%= @subscription.status %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/success.html.erb
<div class="container">
	<div class="alert-wrapper mg-30">
		<div class="alert alert-success" role="alert">
		  <h3>Félicitations!</h3>
		  Votre abonnement a été enregistré avec succès et son traitement commence le plus tôt possible.
		</div>
	</div>
</div>