config/routes.rb
Rails.application.routes.draw do



  resources :contact_forms
  get "pricing/" => "subscription_packs#pricing", as: :pricing
  get "portfolio/cards/:portfolio_id" => "cards#index", as: :portfolio_cards
  resources :cards do    
    get "delete"
  end

  get "invitations/search-users" => "invitations#search_users", as: :search_users

  get "members/organization/:organization_id" => "members#index", as: :organization_members

  resources :members do    
    get "delete"
  end
  resources :invitations do    
    get "delete"

    collection do    
      get "get_services" => "invitations#get_services"
    end
  end
  resources :pages do    
    get "delete"
  end
  
  resources :portfolios do    
    get "delete"
  end

  get "services/organization/:organization_id" => "services#index", as: :organization_services
  post "subscriptions/new" => "subscriptions#new_guest_subscription"
  get "subscriptions/new" => "subscriptions#new_guest_subscription", as: :new_guest_subscription


  #post "subscriptions/new"

  resources :services do    
    get "delete"
  end

  resources :organizations  do    
    get "delete"
  end
  resources :smtp_configs
  resources :organization_types  do    
    get "delete"
  end
  resources :subscriptions  do    
    get "delete"
  end
  resources :subscription_types do    
    get "delete"
  end
  resources :subscription_pack_items do    
    get "delete"
  end
  resources :subscription_packs do    
    get "delete"
  end
  
  resources :subscription_pack_features do    
    get "delete"
  end
  
  resources :activity_fields do    
    get "delete"
  end
  
  resources :permission_items do    
    get "delete"
  end
  resources :features do    
    get "delete"
  end
  

  
  
 
  
  resources :addresses do    
    get "delete"
  end
  
  # Home route.
  root to: "front#home"

  
  get '/robots.:format' => 'pages#robots'
  get '/ads.:format' => 'pages#ads'


  # Named routes.
  get "/home" => "front#home"
  get "/dashboard" => "dashboard#index", as: :dashboard
  get "/landing" => "pages#landing_page", as: :landing_page
  get "/inquiry-success" => "inquiry_forms#success", as: :inquiry_success
  get "/contact-success" => "contact_forms#success", as: :contact_success
  get "ad/success" => "ads#success", as: :ad_success
  get "/subscription-success" => "subscriptions#success", as: :subscription_success

  get "/suscribe" => "pages#newsletter_suscribe", as: :suscribe
  get "/post/:slug" => "blog#show", as: :post_show
  
  get "/search" => "searches#search_properties", as: :search_properties
  
  get "/about-us" => "pages#about_us", as: :about_us
  get "/how-it-work" => "pages#how_it_work", as: :how_it_work
  get "/cgu" => "pages#cgu", as: :cgu
  get "/join-us" => "pages#join_us", as: :join_us
  get "/contact" => "pages#contact", as: :contact
  get "/advertise" => "pages#advertise", as: :advertise
  get "/blog"  => "blog#index", as: :blog
  get "/faq" => "pages#faq", as: :faq
  get "/privacy-policy" => "pages#privacy_policy", as: :privacy_policy
  get "/partenaires" => "pages#partenaires", as: :partnaires
  
  #get '/inquiry_form' => 'contact_email#inquiry', as: :inquiry_email
  #get "/properties/all" => "front#properties", as: :load_all_properties
  get "/profile/:login/edit" => "profile#edit", as: :user_profile
  get 'users/edit' => 'users/registrations#edit', as:  :edit_user_registration
  #get "search" => "properties#search", as: :search_properties
  get "/user/enable/:id" => "custom_users#get_enable", as: :get_enable_user_account
	post "/user/enable/:id" => "custom_users#post_enable", as: :post_enable_user_account
	get "/user/disable/:id" => "custom_users#get_disable", as: :get_disable_user_account
  post "/user/disable/:id" => "custom_users#post_disable", as: :post_disable_user_account
  

  get "/users"     => "custom_users#index", as: :all_users 
  get "/users/unregistered"     => "custom_users#unregistered", as: :unregistered_commission_percentage 
  post "/users/new"     => "custom_users#create", as: :create_user
  get "/users/new"     => "custom_users#new", as: :new_user
  get "/user/edit/:id" => "custom_users#edit", as: :edit_user
  patch "/user/update/:id" => "custom_users#update", as: :udapte_user
  delete "/user/destroy/:id" => "custom_users#destroy", as: :destroy_user
  get "/user/delete/:id" => "custom_users#delete", as: :delete_user

 
  
  scope "account" do 
    resources :profiles 
    get "profile/:uid" => "profiles#edit", as: :edit_account
  end
  #devise_for :users
  resources :permission_roles do 
    get "delete"
  end
  resources :permissions do 
    get "delete"
  end
  resources :roles do 
    get "delete"
  end

  devise_for :users, path: '', controllers: { 
    registrations: "users/registrations",
    confirmations: 'users/confirmations',
    passwords: "users/passwords",
    sessions: "users/sessions"
        
    }, 
    path_names: {
        sign_in: 'login', 
        sign_out: 'logout', 
        password: 'secret', 
        confirmation: 'verification', 
        unlock: 'unblock', 
        registration: 'signup', 
        sign_up: '' 
  }

  devise_scope :user do
    #root to: "users/sessions#new"
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end
 
  # Dynamic error pages
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"
  mount Ckeditor::Engine => '/ckeditor'


  # For mobile API Endpoint
  mount API::Base, at: "/"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :authenticate_user!
	layout("dashboard")
	def index
		@total_users = User.count
		@total_subscriptions = Subscription.count
		@total_organizations = Organization.count
		@total_cards = 0
	end
	def show
	end
end

app/views/layouts/partials/dashboard/navs/_admin-nav.html.erb
<!-- ########## START: LEFT PANEL ########## -->

      <ul class="br-sideleft-menu">
       <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Tableau de bord</span>'), dashboard_path, class: "br-menu-link active" %>
        </li><!-- br-menu-item -->
        


        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-building-o tx-20"></i>
            <span class="menu-item-label">Propriétés</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Tout", properties_path, class: "sub-link" %>
            </li>
             

            
          </ul>
        </li>

        
    
        

        
        
        
       
      </ul><!-- br-sideleft-menu -->

      
       
        
      </div><!-- info-list -->

    <!-- ########## END: LEFT PANEL ########## -->

app/views/layouts/partials/dashboard/navs/_customer-nav.html.erb
<!-- ########## START: LEFT PANEL ########## -->

      <ul class="br-sideleft-menu">
       <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Tableau de bord</span>'), dashboard_path, class: "br-menu-link active" %>
        </li><!-- br-menu-item -->

       

        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-money tx-20"></i>
            <span class="menu-item-label">Opérations</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Dépots", deposits_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Retraits", withdrawals_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Transferts", transfers_path, class: "sub-link" %>
            </li>

           

          </ul>
        </li>


        

       <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-bar-chart tx-20"></i>
            <span class="menu-item-label">Situations</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Mon solde", my_balance_path, class: "sub-link" %>
            </li>

            
          </ul>
        </li>

        
        
       
      </ul><!-- br-sideleft-menu -->

      
       
        
      </div><!-- info-list -->

    <!-- ########## END: LEFT PANEL ########## -->

app/views/layouts/partials/dashboard/navs/_guest-nav.html.erb
<!-- ########## START: LEFT PANEL ########## -->

      <ul class="br-sideleft-menu">
       <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Tableau de bord</span>'), dashboard_path, class: "br-menu-link active" %>
        </li><!-- br-menu-item -->

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Courrier d\'arrivée</span>'), arrival_mails_path, class: "br-menu-link" %>
        </li><!-- br-menu-item -->

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Courrier départ</span>'), departure_mails_path, class: "br-menu-link" %>
        </li><!-- br-menu-item -->



       



         
        
        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-cogs tx-20"></i>
            <span class="menu-item-label">Paramètres</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Utilisateurs", root_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types registre", registry_types_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Registres", registries_path, class: "sub-link" %>
            </li>
             <li class="sub-item">
                <%= link_to  "Services", services_path, class: "sub-link" %>
            </li>
            <li class="sub-item">
                <%= link_to  "Supports", supports_path, class: "sub-link" %>
            </li>
            <li class="sub-item">
                <%= link_to  "Natures", natures_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types correspondant", correspondent_types_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Domaines d'activité", activity_fields_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Correspondants", correspondents_path, class: "sub-link" %>
            </li>

          </ul>
        </li>
       
      </ul><!-- br-sideleft-menu -->

      
       
        
      </div><!-- info-list -->

    <!-- ########## END: LEFT PANEL ########## -->

app/views/layouts/partials/dashboard/navs/_root-nav.html.erb
<!-- ########## START: LEFT PANEL ########## -->

      <ul class="br-sideleft-menu">
       <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Tableau de bord</span>'), dashboard_path, class: "br-menu-link active" %>
        </li><!-- br-menu-item -->

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Courrier d\'arrivée</span>'), arrival_mails_path, class: "br-menu-link" %>
        </li><!-- br-menu-item -->

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Courrier départ</span>'), departure_mails_path, class: "br-menu-link" %>
        </li><!-- br-menu-item -->



       



         
        
        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-cogs tx-20"></i>
            <span class="menu-item-label">Paramètres</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Utilisateurs", root_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types registre", registry_types_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Registres", registries_path, class: "sub-link" %>
            </li>
             <li class="sub-item">
                <%= link_to  "Services", services_path, class: "sub-link" %>
            </li>
            <li class="sub-item">
                <%= link_to  "Supports", supports_path, class: "sub-link" %>
            </li>
            <li class="sub-item">
                <%= link_to  "Natures", natures_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types correspondant", correspondent_types_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Domaines d'activité", activity_fields_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Correspondants", correspondents_path, class: "sub-link" %>
            </li>

          </ul>
        </li>
       
      </ul><!-- br-sideleft-menu -->

      
       
        
      </div><!-- info-list -->

    <!-- ########## END: LEFT PANEL ########## -->

app/views/layouts/partials/dashboard/navs/_superuser-nav.html.erb
<!-- ########## START: LEFT PANEL ########## -->

      <ul class="br-sideleft-menu">
       <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Tableau de bord</span>'), dashboard_path, class: "br-menu-link #{current? "active", dashboard_path}" %>
        </li><!-- br-menu-item -->

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-book tx-20"></i> <span class="menu-item-label">Portfolios</span>'), portfolios_path, class: "br-menu-link" %>
        </li><!-- br-menu-item -->

        
        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-user-plus tx-20"></i> <span class="menu-item-label">Invitations</span>'), invitations_path, class: "br-menu-link" %>
        </li><!-- br-menu-item -->


       <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-list-alt tx-20"></i>
            <span class="menu-item-label">Abonnements</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Liste des abonnements", subscriptions_path, class: "sub-link #{current? "active", subscriptions_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Plans d'abonnement", subscription_packs_path, class: "sub-link #{current? "active", subscription_packs_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Fonctionalités", subscription_pack_features_path, class: "sub-link #{current? "active", subscription_pack_features_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types d'abonnement", subscription_types_path, class: "sub-link #{current? "active", subscription_types_path}" %>
            </li>

      


          </ul>
        </li>


        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-building-o tx-20"></i>
            <span class="menu-item-label">Organisations</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Liste des organisations", organizations_path, class: "sub-link #{current? "active", organizations_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types d'organisation", organization_types_path, class: "sub-link #{current? "active", organization_types_path}" %>
            </li>

            
      


          </ul>
        </li>
         

        
        
         
    



          </ul>
        </li>


        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-file tx-20" aria-hidden="true"></i> <span class="menu-item-label">Pages</span>'), pages_path, class: "br-menu-link #{current? "active", pages_path}" %>

        </li><!-- br-menu-item -->


        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-cog tx-20"></i>
            <span class="menu-item-label">Paramètres</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">

            <li class="sub-item">
                <%= link_to  "Fonctionalités", features_path, class: "sub-link #{current? "active", features_path}" %>
            </li>
            
            <li class="sub-item">
                <%= link_to  "Rôles", roles_path, class: "sub-link #{current? "active", roles_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Droits d'accès", permissions_path, class: "sub-link #{current? "active", permissions_path}" %>
            </li>



            <li class="sub-item">
                <%= link_to  "Utilisateurs", all_users_path, class: "sub-link #{current? "active", all_users_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Domaines d'activité", activity_fields_path, class: "sub-link #{current? "active", activity_fields_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Serveur SMTP", smtp_configs_path, class: "sub-link #{current? "active", smtp_configs_path}" %>
            </li>

            

            



          



          </ul>
        </li>


       
      </ul><!-- br-sideleft-menu -->

      
       
        
      </div><!-- info-list -->

    <!-- ########## END: LEFT PANEL ########## -->

app/views/layouts/partials/dashboard/navs/_user-nav.html.erb
<!-- ########## START: LEFT PANEL ########## -->

      <ul class="br-sideleft-menu">
       <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Tableau de bord</span>'), dashboard_path, class: "br-menu-link #{current? "active", dashboard_path}" %>
        </li><!-- br-menu-item -->

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-id-card-o tx-20"></i> <span class="menu-item-label">Portfolios</span>'), root_path, class: "br-menu-link" %>
        </li><!-- br-menu-item -->
        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-user-plus tx-20"></i> <span class="menu-item-label">Invitations</span>'), root_path, class: "br-menu-link" %>
        </li><!-- br-menu-item -->


       <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-list-alt tx-20"></i>
            <span class="menu-item-label">Abonnements</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Liste des abonnements", subscription_types_path, class: "sub-link #{current? "active", subscription_types_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Plans d'abonnement", subscription_packs_path, class: "sub-link #{current? "active", subscription_packs_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Fonctionalités", subscription_pack_features_path, class: "sub-link #{current? "active", subscription_pack_features_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types d'abonnement", subscription_types_path, class: "sub-link #{current? "active", subscription_types_path}" %>
            </li>

      


          </ul>
        </li>


        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-building-o tx-20"></i>
            <span class="menu-item-label">Organisations</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Liste des organisations", root_path, class: "sub-link #{current? "active", root_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types d'organisation", organization_types_path, class: "sub-link #{current? "active", organization_types_path}" %>
            </li>

            
      


          </ul>
        </li>
         

        
        
         
            



          </ul>
        </li>


        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-cog tx-20"></i>
            <span class="menu-item-label">Paramètres</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Rôles", roles_path, class: "sub-link #{current? "active", roles_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Utilisateurs", all_users_path, class: "sub-link #{current? "active", all_users_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Domaines d'activité", activity_fields_path, class: "sub-link #{current? "active", activity_fields_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Serveur SMTP", smtp_configs_path, class: "sub-link #{current? "active", smtp_configs_path}" %>
            </li>

            

            



          



          </ul>
        </li>


       
      </ul><!-- br-sideleft-menu -->

      
       
        
      </div><!-- info-list -->

    <!-- ########## END: LEFT PANEL ########## -->